swagger: "2.0"
info:
  version: "0.0.1"
  title: Luna Api
# during dev, should point to your local machine
host: localhost:3010
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /userProfiles:
    # binds a127 app logic to a route
    x-swagger-router-controller: userProfiles
    get:
      tags: 
      - userprofile
      summary: "Gets all the user profiles"
      description: "Returns list of user profiles to the caller"
      responses:
        200:
          description: OK
          schema:
            # a pointer to a definition
            $ref: "#/definitions/UserProfile"
          
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
      - userprofile
      summary: "Insert a new user profile"
      description: "Insert a new user profile"
      parameters:
      - name: userProfile
        in: body
        required: true
        schema:
          $ref: "#/definitions/UserProfile"
      responses:
        201:
          description: OK          
          schema:
            # a pointer to a definition
            $ref: "#/definitions/UserProfile"
        405:
          description: "Invalid input"
          
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      tags:
      - userprofile
      summary: Update a user specified by the id
      description: Update a user specified by the id
      parameters:
      - name: userProfile
        in: body
        required: true
        schema:
          # a pointer to a definition
          $ref: "#/definitions/UserProfile"
      responses:
        200:
          description: OK
          schema:
            # a pointer to a definition
            $ref: "#/definitions/UserProfile"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /userProfiles/{id}:
    get:
      tags:
      - userprofile
      summary: "Gets a user profile secified by the id"
      description: "Returns the requested user profile"
      parameters:
      - name: id
        in: path
        required: true
        type: string
        format: uuid
      responses:
        200:
          description: OK
          schema:
            # a pointer to a definition
            $ref: "#/definitions/UserProfile"
        400:
          description: "Invalid id supplied"
        404:
          description: "User not found"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
      - userprofile
      summary: "Deletes a user specified by the id"
      description: "Deletes a user specified by the id"
      parameters:
      - name: id
        in: path
        required: true
        type: string
        format: uuid
      responses:
        200:
          description: OK
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  UserProfile:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for a user
      email:
        type: string
        description: Email address of the user
      displayName:
        type: string
        description: Friendly display name as chosen by the user
      firstName:
        type: string
        description: Users' first name
      lastName:
        type: string
        description: User's last name
      description:
        type: string
        description: Optional field for user's summary of themselves
      picture:
        type: string
        description: URL for user's picture
      fbid:
        type: string
        description: user's facebook Id
      created:
        type: string
        description: Timestamp for when the user record was created
      devices:
        type: array
        description: List of devices used by the user
        items:
          type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
